# Generated by Django 4.2.1 on 2023-06-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='fecha_alta',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 11, 24, 19, 481344)),
        ),
    ]
