# Generated by Django 4.2.1 on 2023-05-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('coordinadores', '0008_alter_coordinador_fecha_alta'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinadores.coordinador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='servicios.servicio'),
            preserve_default=False,
        ),
    ]
