# Generated by Django 4.2.1 on 2023-05-21 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.PositiveBigIntegerField()),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime(2023, 5, 21, 11, 26, 55, 602597))),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
